version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "loom-features"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xrgtl9dspann"
s3_prefix = "loom-features"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
